version: '3.5'
services:
    omfg:
        build:
            context: ..
            dockerfile: docker/dev.dockerfile
        container_name: omfg
        image: atgardner/omfg:dev
        ports:
            - 3000:3000
            - 9229:9229
        tty: true
        volumes:
            - ../:/service
